import { END, START, StateGraph, StateSchema, type GraphNode } from "@langchain/langgraph"
import z from "zod"
import { cohereModel, geminiModel, mistralModel } from "./model.ai.js"
import { createAgent, HumanMessage, providerStrategy } from "langchain"

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge_recommendation: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default("")
    })
})

const solutionNode: GraphNode<typeof state> = async (state) => {
    const [mistral_response, cohere_response] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistral_response.text,
        solution_2: cohere_response.text
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state;

    const judgeAgent = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string()
        })),
        systemPrompt: `Your a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })

    const judgeResponse = await judgeAgent.invoke({
        messages: [new HumanMessage(`
            Problem:${state.problem}
            Solution 1:${state.solution_1}
            Solution 2:${state.solution_2}
            Please evaluate the solutions and provide scores and reasoning.
            `)]
    })

    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgeResponse.structuredResponse

    return {
        judge_recommendation: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge")
    .addEdge("judge", END)
    .compile()

export default async function runGraph(userMessage: string) {
    const result = await graph.invoke({
        problem: userMessage
    })
    return result
}   